version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    # volumes:
    #   - /home/node/app/node_modules
    #   - ./:/home/node/app
